### Endpoint de teste
GET http://localhost:3003/ping


### Endpoint signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Eduardo",
    "email": "eduardo@gmail.com",
    "password": "dudu123"
}

### Endpoint login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "vernizzi@gmail.com",
    "password": "bananinha"
}

### Create product
POST http://localhost:3003/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MjY0MzcxNiwiZXhwIjoxNjYyNzMwMTE2fQ.bZK9d6G5HpBrosEXzcKcPbKgpFLyL3c9gsEAiMi3BLc
Content-Type: application/json

{
    "name": "VESTIDO SLIPDRESS CETIM",
    "tag": ["neutro, balada"]
}

### Get products
GET http://localhost:3003/products

### Get search products by id or name
GET http://localhost:3003/products/search?q=8360

### 6) Get search products by tag
GET http://localhost:3003/products/search/tag?q=balada

### 6) Edit product
PUT http://localhost:3003/products/8360
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MjY0MzcxNiwiZXhwIjoxNjYyNzMwMTE2fQ.bZK9d6G5HpBrosEXzcKcPbKgpFLyL3c9gsEAiMi3BLc
Content-Type: application/json

{
    "name": "VESTIDO BABADOS KNIT"
}

### 7) Delete product
DELETE http://localhost:3003/products/d687b589-9b31-41d7-803d-617d9569848a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MjY0MzcxNiwiZXhwIjoxNjYyNzMwMTE2fQ.bZK9d6G5HpBrosEXzcKcPbKgpFLyL3c9gsEAiMi3BLc